import type { Park } from "@/lib/catalog";

const I = {
  baja: "/images/territories/latam/baja.jpg",
  mexico: "/images/territories/latam/mexico.jpg",
  central: "/images/territories/latam/central.jpg",
  andes: "/images/territories/latam/andes.jpg",
  brazil: "/images/territories/latam/brazil.jpg",
  patagonia: "/images/territories/latam/patagonia.jpg",
};

function row(p: Omit<Park, "territoryId" | "areaUnit">): Park {
  return { ...p, territoryId: "latam", areaUnit: "ha" };
}

/** Drive-to parks from Baja to Tierra del Fuego. Not every national park — the ones with a town for keys. */
export const LATAM_PARKS: Park[] = [
  row({ slug: "san-pedro-martir", name: "Sierra de San Pedro Mártir", state: "Mexico", region: "Mexico & Baja", tagline: "Baja’s high pine, an observatory, and a road the coaches skip.", description: "Ensenada is the town. The park road climbs off the peninsula’s spine. Hosts leave cars that have already seen washboard and a cold night in June.", pickupTown: "Ensenada, Mexico", image: I.baja, established: 1974, acres: "72,911" }),
  row({ slug: "constitucion-1857", name: "Constitución de 1857", state: "Mexico", region: "Mexico & Baja", tagline: "A granite lagoon in the sierra, a day’s drive from the border.", description: "Ensenada again, then the dirt. The lake is the picnic. You want something that likes a rutted last kilometre.", pickupTown: "Ensenada, Mexico", image: I.baja, established: 1962, acres: "5,009" }),
  row({ slug: "cabo-pulmo", name: "Cabo Pulmo", state: "Mexico", region: "Mexico & Baja", tagline: "A reef you snorkel, a village that is the gate.", description: "La Ribera or Cabo Pulmo village. The park is water. The car is for the East Cape road and the hour the sand is still hard.", pickupTown: "La Ribera, Mexico", image: I.baja, established: 1995, acres: "7,111" }),
  row({ slug: "cumbres-monterrey", name: "Cumbres de Monterrey", state: "Mexico", region: "Mexico & Baja", tagline: "A canyon above a city, waterfalls if the rain came.", description: "Santiago, Nuevo León. Chipinque is the city side. Hosts know which cascada still has a lot after 10.", pickupTown: "Santiago, Mexico", image: I.mexico, established: 1939, acres: "177,396" }),
  row({ slug: "pico-orizaba", name: "Pico de Orizaba", state: "Mexico", region: "Mexico & Baja", tagline: "The highest mountain in Mexico, a hut road, a town that knows ice.", description: "Tlachichuca is the classic gate. The volcano is walking. The car is for the hut and the descent that is worse than the climb.", pickupTown: "Tlachichuca, Mexico", image: I.mexico, established: 1937, acres: "19,750" }),
  row({ slug: "palenque", name: "Palenque", state: "Mexico", region: "Mexico & Baja", tagline: "A city in the jungle, howler monkeys at the ticket booth.", description: "Palenque town. The ruins are the park. A car for the site and the waterfall road to Misol-Ha before the coaches.", pickupTown: "Palenque, Mexico", image: I.mexico, established: 1981, acres: "1,772" }),
  row({ slug: "sumidero", name: "Cañón del Sumidero", state: "Mexico", region: "Mexico & Baja", tagline: "A gorge you boat, viewpoints you drive.", description: "Chiapa de Corzo is the boat town. The lookouts are a ridge road. Hosts leave a car that can do both before lunch.", pickupTown: "Chiapa de Corzo, Mexico", image: I.mexico, established: 1980, acres: "21,789" }),
  row({ slug: "basaseachi", name: "Cascada de Basaseachi", state: "Mexico", region: "Mexico & Baja", tagline: "Copper Canyon country, a waterfall, Creel for the keys.", description: "Creel is the railroad town and the porch. The canyon is a week. You want something that likes dirt and a cool night at 2,300 metres.", pickupTown: "Creel, Mexico", image: I.mexico, established: 1981, acres: "5,803" }),
  row({ slug: "sian-kaan", name: "Sian Ka’an", state: "Mexico", region: "Mexico & Baja", tagline: "A biosphere south of Tulum, lagoons, a road that gives up.", description: "Tulum or Felipe Carrillo Puerto. Most of the reserve is boat. The car is for the gate and the beach the buses have not found.", pickupTown: "Tulum, Mexico", image: I.mexico, established: 1986, acres: "528,148" }),
  row({ slug: "nevado-toluca", name: "Nevado de Toluca", state: "Mexico", region: "Mexico & Baja", tagline: "A crater with lakes, an hour from Toluca if the pass is open.", description: "Toluca or Zinacantepec. The road climbs to the crater lot. You want altitude sense and a wind that is not optional.", pickupTown: "Toluca, Mexico", image: I.mexico, established: 1936, acres: "46,764" }),
  row({ slug: "izta-popo", name: "Izta-Popo", state: "Mexico", region: "Mexico & Baja", tagline: "Two volcanoes beside the capital, a pass if the snow allows.", description: "Amecameca. Paso de Cortés is the park. A car for dawn and the day Popo is awake.", pickupTown: "Amecameca, Mexico", image: I.mexico, established: 1935, acres: "39,819" }),

  row({ slug: "manuel-antonio", name: "Manuel Antonio", state: "Costa Rica", region: "Central America", tagline: "The smallest famous park, a beach, a sloth if you are lucky.", description: "Quepos. Tickets sell out. The car is for the gate hour and the day you leave the beach for the coast road.", pickupTown: "Quepos, Costa Rica", image: I.central, established: 1972, acres: "1,983" }),
  row({ slug: "arenal", name: "Volcán Arenal", state: "Costa Rica", region: "Central America", tagline: "A cone that used to glow, a lake, hanging bridges.", description: "La Fortuna. The volcano is a trail and a viewpoint. Hosts leave a car that can take a rain that does not pause.", pickupTown: "La Fortuna, Costa Rica", image: I.central, established: 1991, acres: "12,124" }),
  row({ slug: "corcovado", name: "Corcovado", state: "Costa Rica", region: "Central America", tagline: "The Osa, if you still have a 4x4 and a tide table.", description: "Puerto Jiménez. The park is walking and a ranger station. The car is for the peninsula road that is not always a road.", pickupTown: "Puerto Jiménez, Costa Rica", image: I.central, established: 1975, acres: "42,469" }),
  row({ slug: "rincon-vieja", name: "Rincón de la Vieja", state: "Costa Rica", region: "Central America", tagline: "Mud pots, a dry forest, Guanacaste heat.", description: "Liberia is the town with the airport. The park is a dirt spur. Hosts expect dust and a waterfall swim.", pickupTown: "Liberia, Costa Rica", image: I.central, established: 1973, acres: "14,161" }),
  row({ slug: "tenorio", name: "Tenorio", state: "Costa Rica", region: "Central America", tagline: "Río Celeste, if the rain has not turned it brown.", description: "Bijagua. The blue river is the product. A car for the lot that fills at 8.", pickupTown: "Bijagua, Costa Rica", image: I.central, established: 1976, acres: "12,860" }),
  row({ slug: "chirripo", name: "Chirripó", state: "Costa Rica", region: "Central America", tagline: "The roof of Costa Rica, a summit you walk before dawn.", description: "San Gerardo de Rivas. Permits for the hut. The car stays in the village.", pickupTown: "San Gerardo de Rivas, Costa Rica", image: I.central, established: 1975, acres: "50,150" }),
  row({ slug: "baru", name: "Volcán Barú", state: "Panama", region: "Central America", tagline: "Two oceans from one summit, if the cloud lifts.", description: "Boquete is the town of coffee and cool nights. The road is a 4x4 rumour. Hosts know which hour still has a view.", pickupTown: "Boquete, Panama", image: I.central, established: 1976, acres: "14,325" }),
  row({ slug: "tikal", name: "Tikal", state: "Guatemala", region: "Central America", tagline: "Temples above the canopy, howler monkeys for the alarm.", description: "Flores / Santa Elena. The park is the ruins. A car for the dawn entry and the island after.", pickupTown: "Flores, Guatemala", image: I.central, established: 1955, acres: "57,600" }),
  row({ slug: "el-imposible", name: "El Imposible", state: "El Salvador", region: "Central America", tagline: "El Salvador’s wildest park, a sierra road.", description: "Tacuba. The park is forest and a river. You want something that likes dirt and a grade that is not a rumour.", pickupTown: "Tacuba, El Salvador", image: I.central, established: 1989, acres: "3,820" }),
  row({ slug: "los-volcanes", name: "Los Volcanes", state: "El Salvador", region: "Central America", tagline: "Santa Ana, Izalco and Cerro Verde, three cones in a day.", description: "El Congo or Santa Ana. Santa Ana’s crater is the walk. The car is for the park and the coffee after.", pickupTown: "Santa Ana, El Salvador", image: I.central, established: 1989, acres: "4,500" }),
  row({ slug: "la-tigra", name: "La Tigra", state: "Honduras", region: "Central America", tagline: "Cloud forest above Tegucigalpa, if the cloud lets you look.", description: "Tegucigalpa. Jutiapa is the usual gate. A car for dawn and the fog on the way down.", pickupTown: "Tegucigalpa, Honduras", image: I.central, established: 1980, acres: "24,000" }),
  row({ slug: "celaque", name: "Celaque", state: "Honduras", region: "Central America", tagline: "The roof of Honduras, a colonial town for the keys.", description: "Gracias, Lempira. The park is the mountain. Hosts leave a car that has already seen a village street.", pickupTown: "Gracias, Honduras", image: I.central, established: 1987, acres: "26,600" }),
  row({ slug: "masaya", name: "Volcán Masaya", state: "Nicaragua", region: "Central America", tagline: "A crater you can drive to the rim of, if the gas allows.", description: "Masaya. Santiago viewpoint is the product. A car for the park and Granada after.", pickupTown: "Masaya, Nicaragua", image: I.central, established: 1979, acres: "5,100" }),
  row({ slug: "los-haitises", name: "Los Haitises", state: "Dominican Republic", region: "Central America", tagline: "Mogotes, mangrove, a park you boat.", description: "Sabana de la Mar or Samaná. Most of the park is water. The car is for the dock and the town.", pickupTown: "Sabana de la Mar, Dominican Republic", image: I.central, established: 1976, acres: "82,000" }),

  row({ slug: "cotopaxi", name: "Cotopaxi", state: "Ecuador", region: "Andes", tagline: "A volcano on the equator that still looks like a drawing.", description: "Latacunga. The refuge road is the trip. You want altitude sense and a jacket in July.", pickupTown: "Latacunga, Ecuador", image: I.andes, established: 1975, acres: "33,393" }),
  row({ slug: "cajas", name: "Cajas", state: "Ecuador", region: "Andes", tagline: "A thousand tarns on the way to Cuenca.", description: "Cuenca. The park sits on the highway. Hosts leave a car that likes mist and a trout lunch.", pickupTown: "Cuenca, Ecuador", image: I.andes, established: 1996, acres: "28,544" }),
  row({ slug: "huascaran", name: "Huascarán", state: "Peru", region: "Andes", tagline: "The Cordillera Blanca, a peak on the money, a town that is already high.", description: "Huaraz. The lagunas are a day’s dirt. You want something that has seen 4,000 metres and a colectivo that is not a car.", pickupTown: "Huaraz, Peru", image: I.andes, established: 1975, acres: "340,000" }),
  row({ slug: "paracas", name: "Paracas", state: "Peru", region: "Andes", tagline: "A desert coast, a red beach, boats to the islands.", description: "Paracas town. The reserve road is the loop. Hosts leave water; the fog does the rest.", pickupTown: "Paracas, Peru", image: I.andes, established: 1975, acres: "335,000" }),
  row({ slug: "tayrona", name: "Tayrona", state: "Colombia", region: "Andes", tagline: "Caribbean jungle, a beach you walk to, cars stop at the gate.", description: "Santa Marta. El Zaino is the entrance. The car is for the gate and Taganga after, not for the sand.", pickupTown: "Santa Marta, Colombia", image: I.andes, established: 1964, acres: "15,000" }),
  row({ slug: "los-nevados", name: "Los Nevados", state: "Colombia", region: "Andes", tagline: "Paramo, wax palms in the valley below, a volcano if the cloud allows.", description: "Manizales or Salento. The park road is a paramo. Hosts expect rain that is a season.", pickupTown: "Manizales, Colombia", image: I.andes, established: 1973, acres: "58,300" }),
  row({ slug: "el-cocuy", name: "El Cocuy", state: "Colombia", region: "Andes", tagline: "Sierra Nevada glaciers, a town that is already high.", description: "El Cocuy or Güicán. The park is walking. The car is for the town and the dirt to the gate.", pickupTown: "El Cocuy, Colombia", image: I.andes, established: 1977, acres: "306,000" }),
  row({ slug: "sajama", name: "Sajama", state: "Bolivia", region: "Andes", tagline: "Bolivia’s oldest park, a volcano, geysers on the altiplano.", description: "Sajama village. The mountain is the skyline. A car that likes gravel and a night below freezing in summer.", pickupTown: "Sajama, Bolivia", image: I.andes, established: 1939, acres: "100,230" }),

  row({ slug: "iguacu", name: "Iguaçu", state: "Brazil", region: "Brazil", tagline: "The Brazilian falls, a walkway into the noise.", description: "Foz do Iguaçu. The park bus is the last kilometre. The car is for the gate and the bird park after.", pickupTown: "Foz do Iguaçu, Brazil", image: I.brazil, established: 1939, acres: "185,262" }),
  row({ slug: "chapada-diamantina", name: "Chapada Diamantina", state: "Brazil", region: "Brazil", tagline: "Plateau, caves, a waterfall you can stand behind.", description: "Lençóis is the town. The park is a week of dirt. Hosts leave a car that has already been to Vale do Pati’s trailhead.", pickupTown: "Lençóis, Brazil", image: I.brazil, established: 1985, acres: "152,142" }),
  row({ slug: "lencois-maranhenses", name: "Lençóis Maranhenses", state: "Brazil", region: "Brazil", tagline: "White dunes, rainwater lagoons, a 4x4 that is not optional.", description: "Barreirinhas. The dunes are the park. You drive to the edge and walk. Hosts know the tide of the river crossing.", pickupTown: "Barreirinhas, Brazil", image: I.brazil, established: 1981, acres: "155,000" }),
  row({ slug: "chapada-veadeiros", name: "Chapada dos Veadeiros", state: "Brazil", region: "Brazil", tagline: "Cerrado, quartzite, a waterfall that is a staircase.", description: "Alto Paraíso de Goiás. São Jorge is closer to the gate. A car for the dirt and the altitude that surprises people from the coast.", pickupTown: "Alto Paraíso, Brazil", image: I.brazil, established: 1961, acres: "240,611" }),
  row({ slug: "serra-orgaos", name: "Serra dos Órgãos", state: "Brazil", region: "Brazil", tagline: "Granite fingers above Rio, a trail that starts in a suburb.", description: "Teresópolis or Petrópolis. The Dedo de Deus is the postcard. Hosts leave a car that can sit in a mountain-town street.", pickupTown: "Teresópolis, Brazil", image: I.brazil, established: 1939, acres: "20,024" }),
  row({ slug: "itatiaia", name: "Itatiaia", state: "Brazil", region: "Brazil", tagline: "Brazil’s first national park, a plateau, agulhas negras.", description: "Itatiaia or Penedo. The high part is a dirt road. You want something that likes mist and a cold night near São Paulo.", pickupTown: "Itatiaia, Brazil", image: I.brazil, established: 1937, acres: "28,084" }),
  row({ slug: "aparados-serra", name: "Aparados da Serra", state: "Brazil", region: "Brazil", tagline: "Canyons on the gaucho plateau, a rim you can drive to.", description: "Cambará do Sul. Itaimbezinho is the cut. Hosts expect fog and a fireplace after.", pickupTown: "Cambará do Sul, Brazil", image: I.brazil, established: 1959, acres: "13,100" }),
  row({ slug: "pantanal", name: "Pantanal Matogrossense", state: "Brazil", region: "Brazil", tagline: "A wetland the size of a country, jaguars if the track is open.", description: "Poconé or Cuiabá. The Transpantaneira is the road. You want clearance and a day that starts before the heat.", pickupTown: "Poconé, Brazil", image: I.brazil, established: 1981, acres: "135,000" }),

  row({ slug: "los-glaciares", name: "Los Glaciares", state: "Argentina", region: "Southern Cone", tagline: "Perito Moreno, Fitz Roy if you went north, ice that calves on a schedule.", description: "El Calafate for the glacier, El Chaltén for the granite. Hosts keep cars in both. The ice does not care which you picked.", pickupTown: "El Calafate, Argentina", image: I.patagonia, established: 1937, acres: "726,927" }),
  row({ slug: "nahuel-huapi", name: "Nahuel Huapi", state: "Argentina", region: "Southern Cone", tagline: "The oldest Argentine park, a lake, Bariloche as the porch.", description: "Bariloche or Villa La Angostura. The Seven Lakes road is the trip. A car for the circuit and the chocolate after.", pickupTown: "Bariloche, Argentina", image: I.patagonia, established: 1934, acres: "717,261" }),
  row({ slug: "tierra-del-fuego", name: "Tierra del Fuego", state: "Argentina", region: "Southern Cone", tagline: "The end of the Pan-American, a train that is a tourist, a beaver dam.", description: "Ushuaia. The park is a short drive. The car is for the park and the day you go the other way to Tolhuin.", pickupTown: "Ushuaia, Argentina", image: I.patagonia, established: 1960, acres: "68,909" }),
  row({ slug: "iguazu", name: "Iguazú", state: "Argentina", region: "Southern Cone", tagline: "The Argentine walkways, Devil’s Throat, the other country’s roar.", description: "Puerto Iguazú. The Brazilian side is a different listing. Hosts know which entrance still has a morning slot.", pickupTown: "Puerto Iguazú, Argentina", image: I.brazil, established: 1934, acres: "67,620" }),
  row({ slug: "lanin", name: "Lanín", state: "Argentina", region: "Southern Cone", tagline: "A volcano on the border, araucaria, a lake that is a postcard.", description: "Junín de los Andes. The volcano is the skyline. A car for the lakes and the Chilean pass if it is open.", pickupTown: "Junín de los Andes, Argentina", image: I.patagonia, established: 1937, acres: "412,013" }),
  row({ slug: "los-alerces", name: "Los Alerces", state: "Argentina", region: "Southern Cone", tagline: "Trees older than the rumour, a lake road, Esquel for keys.", description: "Esquel or Trevelin. The alerce grove is a boat. The car is for the park road and the Welsh tea after.", pickupTown: "Esquel, Argentina", image: I.patagonia, established: 1937, acres: "263,000" }),
  row({ slug: "ischigualasto", name: "Ischigualasto", state: "Argentina", region: "Southern Cone", tagline: "Valley of the Moon, a desert loop, fossils if the guide is on.", description: "San Agustín del Valle Fértil. The loop is guided. The car is for the town and Talampaya the same day.", pickupTown: "Valle Fértil, Argentina", image: I.patagonia, established: 1971, acres: "60,370" }),
  row({ slug: "talampaya", name: "Talampaya", state: "Argentina", region: "Southern Cone", tagline: "Red canyons, a park you ride in their vehicle.", description: "Villa Unión. Private cars stop at the gate. Yours is for town and Ischigualasto next door.", pickupTown: "Villa Unión, Argentina", image: I.patagonia, established: 1997, acres: "215,000" }),
  row({ slug: "torres-del-paine", name: "Torres del Paine", state: "Chile", region: "Southern Cone", tagline: "The towers, the wind, a park that fills in December.", description: "Puerto Natales. The park bus exists; a car is for the hours the bus is not. Hosts leave a layer that is not optional.", pickupTown: "Puerto Natales, Chile", image: I.patagonia, established: 1959, acres: "181,414" }),
  row({ slug: "conguillio", name: "Conguillío", state: "Chile", region: "Southern Cone", tagline: "Monkey-puzzle trees, a black lava field, Llaima if it is behaving.", description: "Melipeuco or Curacautín. The park road is ash. You want something that likes a closed gate in winter.", pickupTown: "Melipeuco, Chile", image: I.patagonia, established: 1950, acres: "60,833" }),
  row({ slug: "vicente-perez-rosales", name: "Vicente Pérez Rosales", state: "Chile", region: "Southern Cone", tagline: "Chile’s oldest park, Petrohué, a volcano in the lake.", description: "Puerto Varas. The falls and the lake are the day. Hosts know the ferry to Peulla if you want the crossing.", pickupTown: "Puerto Varas, Chile", image: I.patagonia, established: 1926, acres: "251,000" }),
  row({ slug: "lauca", name: "Lauca", state: "Chile", region: "Southern Cone", tagline: "Altiplano lakes, vicuñas, a town at 3,500 metres.", description: "Putre. Arica is too low for a dawn start. You want altitude sense and a full tank; the next one is a rumour.", pickupTown: "Putre, Chile", image: I.andes, established: 1970, acres: "137,883" }),
  row({ slug: "queulat", name: "Queulat", state: "Chile", region: "Southern Cone", tagline: "A hanging glacier, the Carretera Austral, rain that is a climate.", description: "Puyuhuapi. The hanging glacier is a short walk. The car is the Carretera. Hosts expect mud.", pickupTown: "Puyuhuapi, Chile", image: I.patagonia, established: 1983, acres: "154,093" }),
  row({ slug: "villarrica", name: "Villarrica", state: "Chile", region: "Southern Cone", tagline: "A volcano that still smokes, Pucón as the porch.", description: "Pucón. The ski road in summer is the hike. A car for the lakes and the day the cone is closed.", pickupTown: "Pucón, Chile", image: I.patagonia, established: 1940, acres: "63,000" }),
  row({ slug: "santa-teresa", name: "Santa Teresa", state: "Uruguay", region: "Southern Cone", tagline: "A fortress, a beach, the Atlantic that Uruguay actually uses.", description: "Punta del Diablo or Castillos. The park is coast and a fort. Hosts leave sand in the pedals on purpose.", pickupTown: "Punta del Diablo, Uruguay", image: I.patagonia, established: 1927, acres: "3,000" }),
];

export const LATAM_FEATURED_SLUGS = [
  "torres-del-paine",
  "los-glaciares",
  "manuel-antonio",
  "iguacu",
  "tayrona",
  "chapada-diamantina",
  "san-pedro-martir",
  "cotopaxi",
] as const;

export const LATAM_REGION_FILTERS = [
  { id: "mexico", label: "Mexico & Baja", labelEs: "México y Baja", match: ["Mexico & Baja"] },
  { id: "central", label: "Central America", labelEs: "Centroamérica", match: ["Central America"] },
  { id: "andes", label: "Andes", labelEs: "Andes", match: ["Andes"] },
  { id: "brazil", label: "Brazil", labelEs: "Brasil", match: ["Brazil"] },
  { id: "cone", label: "Southern Cone", labelEs: "Cono Sur", match: ["Southern Cone"] },
] as const;
