import type { Park } from "@/lib/catalog";

const I = {
  alps: "/images/territories/europe/alps.jpg",
  pyrenees: "/images/territories/europe/pyrenees.jpg",
  iberia: "/images/territories/europe/iberia.jpg",
  med: "/images/territories/europe/mediterranean.jpg",
  balkans: "/images/territories/europe/balkans.jpg",
  nordics: "/images/territories/europe/nordics.jpg",
  isles: "/images/territories/europe/isles.jpg",
  central: "/images/territories/europe/central.jpg",
};

function eu(
  row: Omit<Park, "territoryId" | "areaUnit">,
): Park {
  return { ...row, territoryId: "europe", areaUnit: "ha" };
}

/** Flagship drive-to parks. Not every national park in Europe — the ones with a town for keys. */
export const EUROPE_PARKS: Park[] = [
  eu({ slug: "gran-paradiso", name: "Gran Paradiso", state: "Italy", region: "Alps", tagline: "The first Italian park, still a mountain with ibex on it.", description: "Cogne is the valley town. The park road ends; the rest is trail. Hosts leave cars that like hairpins and a frost in September.", pickupTown: "Cogne, Italy", image: I.alps, established: 1922, acres: "71,044" }),
  eu({ slug: "vanoise", name: "Vanoise", state: "France", region: "Alps", tagline: "The French counterpart to Gran Paradiso, across the same massif.", description: "Pralognan is the classic gate. Modane if you came by train. You want something that parks in a village lot and still climbs to the col.", pickupTown: "Pralognan-la-Vanoise, France", image: I.alps, established: 1963, acres: "53,500" }),
  eu({ slug: "ecrins", name: "Écrins", state: "France", region: "Alps", tagline: "High granite, a glacier, and a road that already did the work.", description: "Briançon is the town with bakeries and a gate. La Bérarde if you want the dead-end. Clearance is optional; nerves on the last kilometres are not.", pickupTown: "Briançon, France", image: I.alps, established: 1973, acres: "91,800" }),
  eu({ slug: "swiss-national-park", name: "Swiss National Park", state: "Switzerland", region: "Alps", tagline: "The oldest in the Alps, and you stay on the path.", description: "Zernez is the porch. The park is walking; the car is for the Engadine and the pass. Hosts expect you back before dark because the park is.", pickupTown: "Zernez, Switzerland", image: I.alps, established: 1914, acres: "17,020" }),
  eu({ slug: "hohe-tauern", name: "Hohe Tauern", state: "Austria", region: "Alps", tagline: "Grossglockner, a toll road, and the biggest park in the Eastern Alps.", description: "Matrei or Zell am See. The High Alpine Road is the trip. You want a car that can sit in a viewpoint queue and still like a grade.", pickupTown: "Matrei in Osttirol, Austria", image: I.alps, established: 1981, acres: "185,600" }),
  eu({ slug: "berchtesgaden", name: "Berchtesgaden", state: "Germany", region: "Alps", tagline: "Königssee and a wall of limestone, an hour from Munich.", description: "Berchtesgaden is the town and the station. The lake is a boat; the car is for Jenner, Rossfeld, and the morning before the coaches.", pickupTown: "Berchtesgaden, Germany", image: I.alps, established: 1978, acres: "20,804" }),
  eu({ slug: "triglav", name: "Triglav", state: "Slovenia", region: "Alps", tagline: "The Julian Alps, a lake, and a mountain on the flag.", description: "Bohinjska Bistrica and Lake Bohinj share the south gate. Kranjska Gora the north. Hosts know which Vršič hour still has a pull-out.", pickupTown: "Bohinjska Bistrica, Slovenia", image: I.alps, established: 1981, acres: "83,807" }),
  eu({ slug: "dolomiti-bellunesi", name: "Dolomiti Bellunesi", state: "Italy", region: "Alps", tagline: "The national park in the Dolomites, not the postcard towns.", description: "Belluno and Agordo. Most people mean the UNESCO plateau; this is the park with a name and a gate. A car for the valleys the buses skip.", pickupTown: "Belluno, Italy", image: I.alps, established: 1990, acres: "31,512" }),
  eu({ slug: "stelvio", name: "Stelvio", state: "Italy", region: "Alps", tagline: "A pass with a number, and a park around it.", description: "Bormio is the south town. The pass is the product in summer. You want gears, brakes, and a car that has seen a hairpin before.", pickupTown: "Bormio, Italy", image: I.alps, established: 1935, acres: "130,700" }),

  eu({ slug: "ordesa", name: "Ordesa y Monte Perdido", state: "Spain", region: "Pyrenees", tagline: "A canyon of limestone, and a village that is the gate.", description: "Torla-Ordesa. In season the park bus takes the last kilometres. The car is for the village, Aínsa, and the morning you beat the barrier.", pickupTown: "Torla-Ordesa, Spain", image: I.pyrenees, established: 1918, acres: "15,608" }),
  eu({ slug: "aiguestortes", name: "Aigüestortes", state: "Spain", region: "Pyrenees", tagline: "Tarns, granite, and taxis that are 4x4s.", description: "Espot or Boí. Private cars stop at the barrier; hosts know the taxi hour. Keep something you can leave in a mountain lot.", pickupTown: "Espot, Spain", image: I.pyrenees, established: 1955, acres: "14,119" }),
  eu({ slug: "pyrenees", name: "Pyrénées", state: "France", region: "Pyrenees", tagline: "Gavarnie on one side, a cirque the maps still understate.", description: "Cauterets or Gavarnie. The French park is a string of valleys. A car that likes col roads and a wet dog after the hourdère.", pickupTown: "Cauterets, France", image: I.pyrenees, established: 1967, acres: "45,707" }),

  eu({ slug: "picos-de-europa", name: "Picos de Europa", state: "Spain", region: "Iberia", tagline: "Limestone towers, a gorge road, cheese in the boot.", description: "Cangas de Onís is the east gate. Potes the west. The Desfiladero de los Beyos is the drive; the lakes are a shuttle. Hosts leave a picnic that survives a pass.", pickupTown: "Cangas de Onís, Spain", image: I.iberia, established: 1918, acres: "67,455" }),
  eu({ slug: "sierra-nevada", name: "Sierra Nevada", state: "Spain", region: "Iberia", tagline: "Mainland Spain’s roof, then the Alpujarras.", description: "Capileira or Güéjar Sierra. Granada is too far for a dawn start. You want something that can take a pueblo blanco street and a 3,000-metre road.", pickupTown: "Capileira, Spain", image: I.iberia, established: 1999, acres: "85,883" }),
  eu({ slug: "donana", name: "Doñana", state: "Spain", region: "Iberia", tagline: "A marsh, a dune, and lynx if you are quiet.", description: "El Rocío is the town on sand. The park is a guided track more than a self-drive. The car is for the village and the coast road to Matalascañas.", pickupTown: "El Rocío, Spain", image: I.iberia, established: 1969, acres: "54,252" }),
  eu({ slug: "teide", name: "Teide", state: "Spain", region: "Iberia", tagline: "Europe’s most visited national park, a volcano in the Atlantic.", description: "Vilaflor on the south, La Orotava the north. Summit permits are a separate story. A car that likes altitude and a jacket in August.", pickupTown: "Vilaflor, Spain", image: I.iberia, established: 1954, acres: "18,990" }),
  eu({ slug: "timanfaya", name: "Timanfaya", state: "Spain", region: "Iberia", tagline: "A lava field you are not allowed to walk, so you drive the loop.", description: "Yaiza is the nearest town. The park road is timed. Hosts leave water; the island does the rest.", pickupTown: "Yaiza, Spain", image: I.iberia, established: 1974, acres: "5,107" }),
  eu({ slug: "peneda-geres", name: "Peneda-Gerês", state: "Portugal", region: "Iberia", tagline: "Portugal’s only national park, granite and wolves.", description: "Vila do Gerês. The park is a mesh of villages and a Spanish border. A car for the dam roads and the villages that still have a café.", pickupTown: "Vila do Gerês, Portugal", image: I.iberia, established: 1971, acres: "70,290" }),

  eu({ slug: "cinque-terre", name: "Cinque Terre", state: "Italy", region: "Mediterranean", tagline: "Five villages, a cliff path, and a car you park once.", description: "La Spezia or Monterosso. You do not drive the villages. The car is for the day you leave the trail and want the rest of Liguria.", pickupTown: "La Spezia, Italy", image: I.med, established: 1999, acres: "3,860" }),
  eu({ slug: "vesuvio", name: "Vesuvius", state: "Italy", region: "Mediterranean", tagline: "A crater above a city that still watches it.", description: "Ercolano is the gate. The crater road is a coach circus; hosts know which hour is quieter. Then the coast.", pickupTown: "Ercolano, Italy", image: I.med, established: 1995, acres: "8,482" }),
  eu({ slug: "etna", name: "Etna", state: "Italy", region: "Mediterranean", tagline: "A volcano that is still writing the island.", description: "Nicolosi south, Linguaglossa north. The road keeps getting redrawn. You want something that can take cinders and a closed barrier with grace.", pickupTown: "Nicolosi, Italy", image: I.med, established: 1987, acres: "58,000" }),
  eu({ slug: "calanques", name: "Calanques", state: "France", region: "Mediterranean", tagline: "White rock into blue water, a park that is a city edge.", description: "Cassis or the south of Marseille. Most of the park is on foot or by boat. The car is for the calanque you can still drive toward before the barrier.", pickupTown: "Cassis, France", image: I.med, established: 2012, acres: "8,500" }),
  eu({ slug: "olympus", name: "Olympus", state: "Greece", region: "Mediterranean", tagline: "The mountain, and a town that has always been the gate.", description: "Litochoro. The gorge path starts in town. A car for the coast and the forest road if it is open.", pickupTown: "Litochoro, Greece", image: I.med, established: 1938, acres: "23,880" }),
  eu({ slug: "samaria", name: "Samaria", state: "Greece", region: "Mediterranean", tagline: "The gorge you walk down, if the bus is on time.", description: "Chania is staging; Omalos is the top. You drive to the start and do not drive the gorge. Hosts keep cars for both ends of the day.", pickupTown: "Chania, Greece", image: I.med, established: 1962, acres: "4,850" }),

  eu({ slug: "plitvice", name: "Plitvice Lakes", state: "Croatia", region: "Balkans", tagline: "Boardwalks over water that should not be that colour.", description: "Plitvička Jezera village. Tickets sell out. The car is for the gate you were assigned and the road to the coast after.", pickupTown: "Plitvička Jezera, Croatia", image: I.balkans, established: 1949, acres: "29,685" }),
  eu({ slug: "krka", name: "Krka", state: "Croatia", region: "Balkans", tagline: "Falls you can still swim below, some months.", description: "Skradin is the boat town. Lozovac the car gate. Hosts know which entrance still has shade at noon.", pickupTown: "Skradin, Croatia", image: I.balkans, established: 1985, acres: "10,900" }),
  eu({ slug: "paklenica", name: "Paklenica", state: "Croatia", region: "Balkans", tagline: "A limestone canyon, climbers, and a wind that has a name.", description: "Starigrad-Paklenica. The canyon is walking; the car is for the Velebit road and the afternoon bora.", pickupTown: "Starigrad, Croatia", image: I.balkans, established: 1949, acres: "9,500" }),
  eu({ slug: "durmitor", name: "Durmitor", state: "Montenegro", region: "Balkans", tagline: "A massif, a black lake, and a canyon deeper than the rumour.", description: "Žabljak is the town on the plateau. The Tara canyon is the drive. You want something that likes altitude and a closed pass in May.", pickupTown: "Žabljak, Montenegro", image: I.balkans, established: 1952, acres: "39,000" }),
  eu({ slug: "valbona", name: "Valbona Valley", state: "Albania", region: "Balkans", tagline: "The Accursed Mountains, a valley road, a ferry if you came from Theth.", description: "Valbona village. Theth is the other end of the traverse. Hosts leave cars that have seen a gravel last mile.", pickupTown: "Valbona, Albania", image: I.balkans, established: 1996, acres: "8,000" }),
  eu({ slug: "pirin", name: "Pirin", state: "Bulgaria", region: "Balkans", tagline: "Granite lakes above Bansko, if the lift is not the point.", description: "Bansko and Bansko’s mountain road. The park is UNESCO. A car for the valley and the hut track you are allowed to use.", pickupTown: "Bansko, Bulgaria", image: I.balkans, established: 1962, acres: "40,332" }),
  eu({ slug: "retezat", name: "Retezat", state: "Romania", region: "Balkans", tagline: "The first Romanian park, a lake district in the Carpathians.", description: "Hațeg is the town. Nucșoara the closer gate. Hosts expect mud and a bear-aware cooler.", pickupTown: "Hațeg, Romania", image: I.balkans, established: 1935, acres: "38,047" }),

  eu({ slug: "jotunheimen", name: "Jotunheimen", state: "Norway", region: "Nordics", tagline: "Home of giants, and a road that already climbed.", description: "Lom or Beitostølen. Gjendesheim if you came for Besseggen. You want a car that is happy in a toll tunnel and a frost in July.", pickupTown: "Lom, Norway", image: I.nordics, established: 1980, acres: "115,000" }),
  eu({ slug: "jostedalsbreen", name: "Jostedalsbreen", state: "Norway", region: "Nordics", tagline: "The glacier that still reaches the road, some years.", description: "Sogndal or Jostedal. The arms have names. Hosts leave a wool layer because the ice makes its own weather.", pickupTown: "Sogndal, Norway", image: I.nordics, established: 1991, acres: "131,000" }),
  eu({ slug: "hardangervidda", name: "Hardangervidda", state: "Norway", region: "Nordics", tagline: "A plateau the size of a small country, and a road across it.", description: "Eidfjord or Geilo. The plateau is the park. You want something that can sit in a snowbank in June and still make the ferry.", pickupTown: "Eidfjord, Norway", image: I.nordics, established: 1981, acres: "342,200" }),
  eu({ slug: "sarek", name: "Sarek", state: "Sweden", region: "Nordics", tagline: "No roads in the park. The car is the last one you leave.", description: "Jokkmokk or Kvikkjokk. You drive to the trail. Hosts know the bus that is not a bus and the week the mosquitoes own.", pickupTown: "Jokkmokk, Sweden", image: I.nordics, established: 1909, acres: "197,000" }),
  eu({ slug: "abisko", name: "Abisko", state: "Sweden", region: "Nordics", tagline: "A canyon, a railway, and aurora if the sky agrees.", description: "Abisko is the station and the gate. The car is for the E10 and the days the train does not suit. Hosts leave a headlamp that is not a toy.", pickupTown: "Abisko, Sweden", image: I.nordics, established: 1909, acres: "7,700" }),
  eu({ slug: "vatnajokull", name: "Vatnajökull", state: "Iceland", region: "Nordics", tagline: "Ice the size of a country, and a ring road that skirts it.", description: "Höfn or Skaftafell. Distances lie. A full tank is not optional. Hosts know which glacier lot still has a toilet.", pickupTown: "Höfn, Iceland", image: I.nordics, established: 2008, acres: "1,400,000" }),
  eu({ slug: "thingvellir", name: "Þingvellir", state: "Iceland", region: "Nordics", tagline: "A rift you can walk, and a parliament that started in a field.", description: "Laugarvatn or Selfoss. The Golden Circle is the rest of the day. A car for the lot and the road that is never empty and still worth it.", pickupTown: "Laugarvatn, Iceland", image: I.nordics, established: 1930, acres: "9,270" }),
  eu({ slug: "oulanka", name: "Oulanka", state: "Finland", region: "Nordics", tagline: "A river canyon and the bear’s ring, if you walk it.", description: "Kuusamo is the town. The park is a suspension bridge and a rapids. Hosts leave mosquito sense and a car that likes forest roads.", pickupTown: "Kuusamo, Finland", image: I.nordics, established: 1956, acres: "29,000" }),

  eu({ slug: "lake-district", name: "Lake District", state: "England", region: "British Isles", tagline: "The busiest park in Europe, if you count the fells as a park.", description: "Keswick or Ambleside. UK national parks are lived-in landscapes, not a ranger gate. The car is for the pass the coach will not take. Hosts expect wet dogs.", pickupTown: "Keswick, England", image: I.isles, established: 1951, acres: "236,200" }),
  eu({ slug: "peak-district", name: "Peak District", state: "England", region: "British Isles", tagline: "The first UK national park, an hour from a million people.", description: "Bakewell or Castleton. Edges and dales. A car that fits a village street and still makes the Snake Pass.", pickupTown: "Bakewell, England", image: I.isles, established: 1951, acres: "143,700" }),
  eu({ slug: "eryri", name: "Eryri", state: "Wales", region: "British Isles", tagline: "Snowdon, if you still call it that, and a park that is the mountain.", description: "Betws-y-Coed or Llanberis. The summit is a path or a railway. The car is for the valleys the crowds skip.", pickupTown: "Betws-y-Coed, Wales", image: I.isles, established: 1951, acres: "213,200" }),
  eu({ slug: "bannau-brycheiniog", name: "Bannau Brycheiniog", state: "Wales", region: "British Isles", tagline: "The Beacons, if you learned the old name first.", description: "Brecon. The road over the gap is the trip. Hosts leave a map that is not your phone.", pickupTown: "Brecon, Wales", image: I.isles, established: 1957, acres: "134,700" }),
  eu({ slug: "pembrokeshire-coast", name: "Pembrokeshire Coast", state: "Wales", region: "British Isles", tagline: "A park that is a coastline, and a path that never quite ends.", description: "St Davids is the smallest city. The car is for the coves. Hosts expect sand in the pedals.", pickupTown: "St Davids, Wales", image: I.isles, established: 1952, acres: "62,000" }),
  eu({ slug: "cairngorms", name: "Cairngorms", state: "Scotland", region: "British Isles", tagline: "The biggest park in Britain, a plateau, and a town that already has the cars.", description: "Aviemore is the gate. The plateau is weather. You want something that can take a ski road in June and a distillery after.", pickupTown: "Aviemore, Scotland", image: I.isles, established: 2003, acres: "452,800" }),
  eu({ slug: "loch-lomond", name: "Loch Lomond & The Trossachs", state: "Scotland", region: "British Isles", tagline: "The loch you have already seen, and the hills behind it.", description: "Balloch or Callander. Glasgow is too close to be the pickup. Hosts know which lochside lot still has a space at 10.", pickupTown: "Balloch, Scotland", image: I.isles, established: 2002, acres: "186,500" }),
  eu({ slug: "killarney", name: "Killarney", state: "Ireland", region: "British Isles", tagline: "Lakes, a jaunting car, and a park that is a town’s back garden.", description: "Killarney. The Ring of Kerry is the rest of the day. A car for Muckross and the gap, not for the jaunting car.", pickupTown: "Killarney, Ireland", image: I.isles, established: 1932, acres: "10,236" }),
  eu({ slug: "connemara", name: "Connemara", state: "Ireland", region: "British Isles", tagline: "Bog, quartzite, and a sky that does the work.", description: "Clifden or Letterfrack. The park is small; the landscape is not. Hosts leave a rain shell that has already been used.", pickupTown: "Clifden, Ireland", image: I.isles, established: 1980, acres: "2,957" }),

  eu({ slug: "bavarian-forest", name: "Bavarian Forest", state: "Germany", region: "Central Europe", tagline: "Germany’s first national park, a forest that is allowed to fall down.", description: "Spiegelau or Grafenau. The Czech Šumava is the other half. A quiet car for the tree-top walk and the lynx enclosure you will pretend you did not enjoy.", pickupTown: "Spiegelau, Germany", image: I.central, established: 1970, acres: "24,250" }),
  eu({ slug: "saxon-switzerland", name: "Saxon Switzerland", state: "Germany", region: "Central Europe", tagline: "Sandstone towers, a river, and a ferry that is a tradition.", description: "Bad Schandau. The Bastei is the postcard. The car is for the valleys the coaches cannot thread.", pickupTown: "Bad Schandau, Germany", image: I.central, established: 1990, acres: "9,350" }),
  eu({ slug: "ceske-svycarsko", name: "Bohemian Switzerland", state: "Czechia", region: "Central Europe", tagline: "The other half of the sandstone, and a gate at Hřensko.", description: "Hřensko. Pravčická brána is the arch. You park and walk; the car is for the gorge road.", pickupTown: "Hřensko, Czechia", image: I.central, established: 2000, acres: "7,900" }),
  eu({ slug: "tatra-poland", name: "Tatra", state: "Poland", region: "Central Europe", tagline: "The Polish high country, and a town that knows it.", description: "Zakopane. The park starts where the coaches stop. Hosts leave a car for Morskie Oko’s lot and the days you skip the cablecar.", pickupTown: "Zakopane, Poland", image: I.central, established: 1954, acres: "21,197" }),
  eu({ slug: "tatra-slovakia", name: "Tatra", state: "Slovakia", region: "Central Europe", tagline: "The other Tatra, a tram, and a high trail.", description: "Tatranská Lomnica or Starý Smokovec. The mountain railway is part of the trip. A car for the valley road.", pickupTown: "Tatranská Lomnica, Slovakia", image: I.central, established: 1948, acres: "73,800" }),
  eu({ slug: "bialowieza", name: "Białowieża", state: "Poland", region: "Central Europe", tagline: "The last lowland forest, and bison if you go in with a guide.", description: "Białowieża village. Strict reserve is guided. The car is for the village and the Belarus fence you will notice.", pickupTown: "Białowieża, Poland", image: I.central, established: 1932, acres: "10,517" }),
  eu({ slug: "wadden-sea", name: "Schleswig-Holstein Wadden Sea", state: "Germany", region: "Central Europe", tagline: "A park that is a tide, if you time it.", description: "Tönning or Husum. The mudflat is the park. A car for the dike road and the hour the water comes back.", pickupTown: "Tönning, Germany", image: I.central, established: 1985, acres: "441,500" }),
];

export const EUROPE_FEATURED_SLUGS = [
  "cairngorms",
  "plitvice",
  "teide",
  "jotunheimen",
  "lake-district",
  "triglav",
  "ordesa",
  "cinque-terre",
] as const;

export const EUROPE_REGION_FILTERS = [
  { id: "alps", label: "Alps", match: ["Alps"] },
  { id: "pyrenees", label: "Pyrenees", match: ["Pyrenees"] },
  { id: "iberia", label: "Iberia & islands", match: ["Iberia"] },
  { id: "mediterranean", label: "Mediterranean", match: ["Mediterranean"] },
  { id: "balkans", label: "Balkans", match: ["Balkans"] },
  { id: "nordics", label: "Nordics", match: ["Nordics"] },
  { id: "isles", label: "British Isles", match: ["British Isles"] },
  { id: "central", label: "Central Europe", match: ["Central Europe"] },
] as const;
