/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GetTheAppRouteImport } from './routes/get-the-app'
import { Route as HostRouteImport } from './routes/host'
import { Route as HostAgreementRouteImport } from './routes/host-agreement'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BookCarIdRouteImport } from './routes/book/$carId'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsCarIdRouteImport } from './routes/cars/$carId'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as HelpSlugRouteImport } from './routes/help/$slug'
import { Route as ParksIndexRouteImport } from './routes/parks/index'
import { Route as ParksParkSlugRouteImport } from './routes/parks/$parkSlug'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as TripsTripIdRouteImport } from './routes/trips/$tripId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTheAppRoute = GetTheAppRouteImport.update({
  id: '/get-the-app',
  path: '/get-the-app',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HostAgreementRoute = HostAgreementRouteImport.update({
  id: '/host-agreement',
  path: '/host-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCarIdRoute = BookCarIdRouteImport.update({
  id: '/book/$carId',
  path: '/book/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/help/$slug',
  path: '/help/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksIndexRoute = ParksIndexRouteImport.update({
  id: '/parks/',
  path: '/parks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksParkSlugRoute = ParksParkSlugRouteImport.update({
  id: '/parks/$parkSlug',
  path: '/parks/$parkSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/claims': typeof ClaimsRoute
  '/favorites': typeof FavoritesRoute
  '/get-the-app': typeof GetTheAppRoute
  '/host': typeof HostRoute
  '/host-agreement': typeof HostAgreementRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/book/$carId': typeof BookCarIdRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/help/$slug': typeof HelpSlugRoute
  '/parks/$parkSlug': typeof ParksParkSlugRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/cars/': typeof CarsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/parks/': typeof ParksIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/claims': typeof ClaimsRoute
  '/favorites': typeof FavoritesRoute
  '/get-the-app': typeof GetTheAppRoute
  '/host': typeof HostRoute
  '/host-agreement': typeof HostAgreementRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/book/$carId': typeof BookCarIdRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/help/$slug': typeof HelpSlugRoute
  '/parks/$parkSlug': typeof ParksParkSlugRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/cars': typeof CarsIndexRoute
  '/help': typeof HelpIndexRoute
  '/parks': typeof ParksIndexRoute
  '/trips': typeof TripsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/claims': typeof ClaimsRoute
  '/favorites': typeof FavoritesRoute
  '/get-the-app': typeof GetTheAppRoute
  '/host': typeof HostRoute
  '/host-agreement': typeof HostAgreementRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/protection': typeof ProtectionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/book/$carId': typeof BookCarIdRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/help/$slug': typeof HelpSlugRoute
  '/parks/$parkSlug': typeof ParksParkSlugRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/cars/': typeof CarsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/parks/': typeof ParksIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/claims'
    | '/favorites'
    | '/get-the-app'
    | '/host'
    | '/host-agreement'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/protection'
    | '/support'
    | '/terms'
    | '/book/$carId'
    | '/cars/$carId'
    | '/help/$slug'
    | '/parks/$parkSlug'
    | '/trips/$tripId'
    | '/cars/'
    | '/help/'
    | '/parks/'
    | '/trips/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/claims'
    | '/favorites'
    | '/get-the-app'
    | '/host'
    | '/host-agreement'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/protection'
    | '/support'
    | '/terms'
    | '/book/$carId'
    | '/cars/$carId'
    | '/help/$slug'
    | '/parks/$parkSlug'
    | '/trips/$tripId'
    | '/cars'
    | '/help'
    | '/parks'
    | '/trips'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/claims'
    | '/favorites'
    | '/get-the-app'
    | '/host'
    | '/host-agreement'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/protection'
    | '/support'
    | '/terms'
    | '/book/$carId'
    | '/cars/$carId'
    | '/help/$slug'
    | '/parks/$parkSlug'
    | '/trips/$tripId'
    | '/cars/'
    | '/help/'
    | '/parks/'
    | '/trips/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ClaimsRoute: typeof ClaimsRoute
  FavoritesRoute: typeof FavoritesRoute
  GetTheAppRoute: typeof GetTheAppRoute
  HostRoute: typeof HostRoute
  HostAgreementRoute: typeof HostAgreementRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectionRoute: typeof ProtectionRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BookCarIdRoute: typeof BookCarIdRoute
  CarsCarIdRoute: typeof CarsCarIdRoute
  HelpSlugRoute: typeof HelpSlugRoute
  ParksParkSlugRoute: typeof ParksParkSlugRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  ParksIndexRoute: typeof ParksIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-the-app': {
      id: '/get-the-app'
      path: '/get-the-app'
      fullPath: '/get-the-app'
      preLoaderRoute: typeof GetTheAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-agreement': {
      id: '/host-agreement'
      path: '/host-agreement'
      fullPath: '/host-agreement'
      preLoaderRoute: typeof HostAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$carId': {
      id: '/book/$carId'
      path: '/book/$carId'
      fullPath: '/book/$carId'
      preLoaderRoute: typeof BookCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/help/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/': {
      id: '/parks/'
      path: '/parks'
      fullPath: '/parks/'
      preLoaderRoute: typeof ParksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/$parkSlug': {
      id: '/parks/$parkSlug'
      path: '/parks/$parkSlug'
      fullPath: '/parks/$parkSlug'
      preLoaderRoute: typeof ParksParkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ClaimsRoute: ClaimsRoute,
  FavoritesRoute: FavoritesRoute,
  GetTheAppRoute: GetTheAppRoute,
  HostRoute: HostRoute,
  HostAgreementRoute: HostAgreementRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectionRoute: ProtectionRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BookCarIdRoute: BookCarIdRoute,
  CarsCarIdRoute: CarsCarIdRoute,
  HelpSlugRoute: HelpSlugRoute,
  ParksParkSlugRoute: ParksParkSlugRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  CarsIndexRoute: CarsIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  ParksIndexRoute: ParksIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
